# Generated by Django 2.0.3 on 2018-03-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=150, verbose_name='Tresc komentarza')),
                ('data_dod', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania komentarza')),
            ],
        ),
    ]
