# Generated by Django 2.0.3 on 2018-03-11 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('komiksy', '0002_comment_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comics', models.FileField(upload_to='images/')),
                ('tag', models.CharField(max_length=50, verbose_name='Tag')),
                ('type', models.CharField(max_length=50, verbose_name='Rodzaj komiksu')),
                ('title', models.CharField(max_length=50, verbose_name='Tytyl')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('public', models.BooleanField(default=1)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'komiksy',
                'verbose_name': 'komiks',
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
