# Generated by Django 2.0.3 on 2018-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0003_auto_20180311_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='comics',
            field=models.ImageField(upload_to='media'),
        ),
    ]
