# Generated by Django 2.0.3 on 2018-03-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0004_auto_20180311_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='public',
            new_name='publiczny',
        ),
    ]
