# Generated by Django 2.0.3 on 2018-03-12 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0005_auto_20180312_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comics', to=settings.AUTH_USER_MODEL),
        ),
    ]
