# Generated by Django 2.0.3 on 2018-03-12 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0006_auto_20180312_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
