# Generated by Django 2.0.3 on 2018-04-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0009_auto_20180402_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='text1',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Text for first character'),
        ),
        migrations.AddField(
            model_name='elements',
            name='text2',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Text for second character'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='comics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komiksy.Comic'),
        ),
    ]
