# Generated by Django 2.0.3 on 2018-04-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0010_auto_20180402_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='comics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='komiksy.Comic'),
        ),
    ]
