# Generated by Django 2.0.3 on 2018-04-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0012_auto_20180402_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, null=True, upload_to='media')),
                ('character1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('character2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('chat1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('chat2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('text1', models.CharField(default=' ', max_length=50, verbose_name='Text for first character')),
                ('text2', models.CharField(default=' ', max_length=50, verbose_name='Text for second character')),
            ],
        ),
        migrations.RemoveField(
            model_name='elements',
            name='comics',
        ),
        migrations.DeleteModel(
            name='Elements',
        ),
        migrations.AddField(
            model_name='comic',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='komiksy.Elementy'),
        ),
    ]
