# Generated by Django 2.0.3 on 2018-04-03 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0013_auto_20180402_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='element',
        ),
        migrations.AddField(
            model_name='elementy',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='komiksy.Comic'),
        ),
        migrations.AlterField(
            model_name='elementy',
            name='text1',
            field=models.CharField(blank=True, default=' ', max_length=50, verbose_name='Tekst dla pierwszej postaci'),
        ),
        migrations.AlterField(
            model_name='elementy',
            name='text2',
            field=models.CharField(blank=True, default=' ', max_length=50, verbose_name='Tekst dla drugiej postaci'),
        ),
    ]
