# Generated by Django 2.0.3 on 2018-04-04 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0014_auto_20180403_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementy',
            name='element',
        ),
        migrations.AddField(
            model_name='comic',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='komiksy.Elementy'),
        ),
    ]
