# Generated by Django 2.0.3 on 2018-04-04 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0016_auto_20180404_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='elementy',
            new_name='element',
        ),
    ]
