# Generated by Django 2.0.3 on 2018-04-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0018_auto_20180405_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='tag',
            field=models.CharField(default=' ', max_length=50, verbose_name='tag'),
        ),
    ]
