# Generated by Django 2.0.3 on 2018-04-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0019_comic_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='tag',
        ),
    ]
