# Generated by Django 2.0.3 on 2018-04-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0020_remove_comic_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementy',
            name='text1',
            field=models.CharField(blank=True, default=' ', max_length=250, verbose_name='Tekst dla pierwszej postaci'),
        ),
        migrations.AlterField(
            model_name='elementy',
            name='text2',
            field=models.CharField(blank=True, default=' ', max_length=250, verbose_name='Tekst dla drugiej postaci'),
        ),
    ]
