# Generated by Django 2.0.3 on 2018-04-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0021_auto_20180408_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementy',
            name='text1',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Tekst dla pierwszej postaci'),
        ),
        migrations.AlterField(
            model_name='elementy',
            name='text2',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Tekst dla drugiej postaci'),
        ),
    ]
