# Generated by Django 2.0.3 on 2018-04-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0022_auto_20180408_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='comic',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='comic',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
