# Generated by Django 2.0.3 on 2018-04-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0023_auto_20180408_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='vote_score',
        ),
    ]
