# Generated by Django 2.0.3 on 2018-04-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0029_auto_20180409_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_fav',
            field=models.BooleanField(default=0),
        ),
    ]
