# Generated by Django 2.0.3 on 2018-04-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0030_favorite_is_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='is_fav',
        ),
    ]
