# Generated by Django 2.0.3 on 2018-04-10 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('komiksy', '0031_remove_favorite_is_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='comic',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='votes',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komiksy.Comic'),
        ),
        migrations.AddField(
            model_name='votes',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
