# Generated by Django 2.0.3 on 2018-04-15 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komiksy', '0034_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='komiksy.Comic'),
        ),
    ]
